vim.keymap.set('n', '<F5>', function() require('dap').continue() end, { desc = 'DAP continue' })
vim.keymap.set('n', '<F10>', function() require('dap').step_over() end, { desc = 'DAP stepover' })
vim.keymap.set('n', '<F11>', function() require('dap').step_into() end, { desc = 'DAP step into' })
vim.keymap.set('n', '<F12>', function() require('dap').step_out() end, { desc = 'DAP step out' })
vim.keymap.set('n', '<Leader>bb', function() require('dap').toggle_breakpoint() end, { desc = 'DAP toggle breakpoint' })
vim.keymap.set('n', '<Leader>bB', function()
  require('dap').toggle_breakpoint(vim.fn.input('Breakpoint condition: '))
end, { desc = "toggle conditional breakpoint" })
vim.keymap.set('n', '<Leader>lp',
  function() require('dap').set_breakpoint(nil, nil, vim.fn.input('Log point message: ')) end,
  { desc = 'DAP breakpoint with log message' })
vim.keymap.set('n', '<Leader>dr', function() require('dap').repl.open() end, { desc = 'DAP open REPL' })
vim.keymap.set('n', '<Leader>dl', function() require('dap').run_last() end, { desc = 'DAP run last' })
vim.keymap.set({ 'n', 'v' }, '<Leader>dh', function()
  require('dap.ui.widgets').hover()
end, { desc = 'DAP hover' })
vim.keymap.set({ 'n', 'v' }, '<Leader>dp', function()
  require('dap.ui.widgets').preview()
end, { desc = 'DAP widgets preview' })
vim.keymap.set('n', '<Leader>df', function()
  local widgets = require('dap.ui.widgets')
  widgets.centered_float(widgets.frames)
end, { desc = 'DAP widgets frames' })
vim.keymap.set('n', '<Leader>ds', function()
  local widgets = require('dap.ui.widgets')
  widgets.centered_float(widgets.scopes)
end, { desc = 'DAP widgets scopes' })
