require('plugin_settings.lualine')
require('plugin_settings.colorizer')
require('plugin_settings.treesitter')
require('plugin_settings.telescope')
require('plugin_settings.nvimtree')
require('plugin_settings.autopairs')
require('plugin_settings.gitsigns')
require('plugin_settings.bufferline')
